[package]
name = "blockchain"
version = "1.0.0"
edition = "2021"

[dependencies]
sha256 = "1.0.3"
chrono = "0.4.19"
url = "2.2.2"
actix-web = "3.3.3"
actix-rt = "1.1.1"
serde = "1.0.133"
serde_json = "1.0.74"
reqwest = {version = "0.11.8", features = ["json"]}
